################### Jmxproxybeat Configuration Example #########################

############################# Jmxproxybeat ######################################

jmxproxybeat:
  # Defines how often an event is sent to the output
  period: 10s

  # Defines list of sockets where Tomcat listen.
  urls: ["http://127.0.0.1:8080"]

  # Defines authentication for Tomcat's manager servlet
  authentication:
    username: "tomcat"
    password: "s3cret"

  # Defines SSL configuration.
  #ssl:
    #cafile: "/path/to/ca/CA.pem"

  beans:
    - bean:
      name: java.lang:type=Memory
      attributes:
        - attribute:
          name: HeapMemoryUsage
        - attribute:
          name: NonHeapMemoryUsage
      keys:
        - committed
        - init
        - max
        - used
    - bean:
      name: java.lang:type=Threading
      attributes:
        - attribute:
          name: CurrentThreadCpuTime
        - attribute:
          name: CurrentThreadUserTime
        - attribute:
          name: DaemonThreadCount
        - attribute:
          name: ThreadCount
        - attribute:
          name: TotalStartedThreadCount
        - attribute:
          name: PeakThreadCount
    - bean:
      name: java.lang:type=ClassLoading
      attributes:
        - attribute:
          name: LoadedClassCount
        - attribute:
          name: TotalLoadedClassCount
        - attribute:
          name: UnloadedClassCount
    - bean:
      name: java.lang:type=OperatingSystem
      attributes:
        - attribute:
          name: AvailableProcessors
        - attribute:
          name: CommittedVirtualMemorySize
        - attribute:
          name: FreePhysicalMemorySize
        - attribute:
          name: FreeSwapSpaceSize
        - attribute:
          name: MaxFileDescriptorCount
        - attribute:
          name: OpenFileDescriptorCount
        - attribute:
          name: ProcessCpuLoad
        - attribute:
          name: ProcessCpuTime
        - attribute:
          name: SystemCpuLoad
        - attribute:
          name: SystemLoadAverage
        - attribute:
          name: TotalPhysicalMemorySize
        - attribute:
          name: TotalSwapSpaceSize

#================================ General =====================================

# The name of the shipper that publishes the network data. It can be used to group
# all the transactions sent by a single shipper in the web interface.
#name:

# The tags of the shipper are included in their own field with each
# transaction published.
#tags: ["service-X", "web-tier"]

# Optional fields that you can specify to add additional information to the
# output.
#fields:
#  env: staging

#================================ Outputs =====================================

# Configure what outputs to use when sending the data collected by the beat.
# Multiple outputs may be used.

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["localhost:9200"]

  # Optional protocol and basic auth credentials.
  #protocol: "https"
  #username: "elastic"
  #password: "changeme"

#----------------------------- Logstash output --------------------------------
#output.logstash:
  # The Logstash hosts
  #hosts: ["localhost:5044"]

  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"

#================================ Logging =====================================

# Sets log level. The default log level is info.
# Available log levels are: critical, error, warning, info, debug
#logging.level: debug

# At debug level, you can selectively enable logging only for some components.
# To enable all selectors use ["*"]. Examples of other selectors are "beat",
# "publish", "service".
#logging.selectors: ["*"]
